# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OlLjrzBOc3W-GJNkHN-rtFvQPfAyX3uS

# Proyek Klasifikasi Gambar: CIFAR-10
- **Nama:** Nikola Izzan Ar Rasheed
- **Email:** izzannikola@student.ub.ac.id
- **ID Dicoding:** nikolaizzan

## Import Semua Packages/Library yang Digunakan
"""

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt
import numpy as np

"""## Data Preparation

### Data Loading
"""

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

"""### Data Preprocessing

#### Split Dataset
"""

x_train, x_val, y_train, y_val = train_test_split(
    x_train, y_train, test_size=0.2, random_state=123
)

print(f"Train samples: {x_train.shape[0]}")
print(f"Validation samples: {x_val.shape[0]}")
print(f"Test samples: {x_test.shape[0]}")

# List nama kelas CIFAR-10
class_names = [
    'airplane', 'automobile', 'bird', 'cat', 'deer',
    'dog', 'frog', 'horse', 'ship', 'truck'
]

print(f"Jumlah kelas: {len(class_names)}")
print("Daftar kelas:")
for idx, name in enumerate(class_names):
    print(f"{idx}: {name}")

fig, axes = plt.subplots(2, 5, figsize=(15, 7))  # 2 rows, 5 columns

for i in range(10):
    ax = axes[i // 5, i % 5]

    # Ambil gambar dari data CIFAR-10
    img = x_train[y_train.flatten() == i][0]  # Ambil gambar pertama dari kelas i
    ax.imshow(img)
    ax.set_title(class_names[i])
    ax.axis('off')  # Matikan axis

plt.tight_layout()
plt.show()

IMG_SIZE = (128, 128)
BATCH_SIZE = 32

def preprocess(x, y):
    x = tf.image.resize(x, IMG_SIZE)
    x = preprocess_input(x)
    return x, y

train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_ds = train_ds.map(preprocess).shuffle(1000).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

val_ds = tf.data.Dataset.from_tensor_slices((x_val, y_val))
val_ds = val_ds.map(preprocess).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test))
test_ds = test_ds.map(preprocess).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

# Data Augmentation
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip('horizontal'),
    layers.RandomRotation(0.05),
    layers.RandomZoom(0.05),
])

"""## Modelling"""

# Modelling
num_classes = 10

base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(128, 128, 3))
base_model.trainable = False

model = Sequential([
    layers.Input(shape=(128, 128, 3)),

    data_augmentation,

    layers.Lambda(preprocess_input),
    base_model,

    layers.Conv2D(32, (3,3), activation='relu', padding='same'),
    layers.MaxPooling2D((2,2)),
    layers.BatchNormalization(),

    layers.Conv2D(64, (3,3), activation='relu', padding='same'),
    layers.MaxPooling2D((2,2)),
    layers.BatchNormalization(),

    layers.GlobalAveragePooling2D(),

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),

    layers.Dense(num_classes, activation='softmax')
])

# Compile model
model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# Callback
early_stopping = EarlyStopping(monitor='val_loss', patience=7, restore_best_weights=True)
checkpoint = ModelCheckpoint('best_model.h5', monitor='val_accuracy', save_best_only=True)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    callbacks=[early_stopping, checkpoint]
)

base_model.trainable = True

model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

fine_tune_epochs = 40

history_finetune = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=fine_tune_epochs,
    initial_epoch=history.epoch[-1],
    callbacks=[early_stopping, checkpoint]
)

"""## Evaluasi dan Visualisasi"""

test_loss, test_acc = model.evaluate(test_ds)
print(f"\nTest accuracy: {test_acc:.4f}")

train_loss, train_acc = model.evaluate(train_ds)
print(f"\nTrain accuracy: {train_acc:.4f}")

val_loss, val_acc = model.evaluate(val_ds)
print(f"\nValidation accuracy: {val_acc:.4f}")

plt.plot(history_finetune.history['accuracy'], label='Training Accuracy')
plt.plot(history_finetune.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title('Training vs Validation Accuracy')
plt.show()

plt.plot(history_finetune.history['loss'], label='Training Loss')
plt.plot(history_finetune.history['val_loss'], label='Validation Loss')
plt.legend()
plt.title('Training vs Validation Loss')
plt.show()

"""## Konversi Model"""

# SavedModel
model.export('saved_model/')

# TF-Lite
converter = tf.lite.TFLiteConverter.from_saved_model('saved_model/')
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS
]
tflite_model = converter.convert()

with open('model.tflite', 'wb') as f:
    f.write(tflite_model)

# TFJS
# !pip install tensorflowjs

import tensorflowjs as tfjs

tfjs.converters.save_keras_model(model, 'tfjs_model')

"""## Inference (Optional)"""

from tensorflow.keras.preprocessing import image
import numpy as np
from google.colab import files
from PIL import Image

uploaded = files.upload()

model = tf.saved_model.load('/content/saved_model/')
infer = model.signatures['serving_default']

for img_path in uploaded.keys():
    img = Image.open(img_path).convert('RGB')
    img = img.resize((128, 128))
    img_array = image.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)

    input_tensor = tf.convert_to_tensor(img_array)

    predictions = infer(input_tensor)

    output_tensor = list(predictions.values())[0].numpy()

    predicted_class = class_names[np.argmax(output_tensor[0])]

    print(f"Predicted class for {img_path}: {predicted_class}")